long bitMatch(long, long);
long test_bitMatch(long, long);
long implication(long, long);
long test_implication(long, long);
long leastBitPos(long);
long test_leastBitPos(long);
long oddBits(void);
long test_oddBits(void);
long replaceByte(long, long, long);
long test_replaceByte(long, long, long);
long conditional(long, long, long);
long test_conditional(long, long, long);
long logicalShift(long, long);
long test_logicalShift(long, long);
long leftBitCount(long);
long test_leftBitCount(long);
long bitParity(long);
long test_bitParity(long);
long dividePower2(long, long);
long test_dividePower2(long, long);
long isGreater(long, long);
long test_isGreater(long, long);
long trueFiveEighths(long);
long test_trueFiveEighths(long);
